<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" />

<!-- favicon -->
<link rel="icon" type="image/png" href="https://rankalytics.com/assets/images/favicon.png">
<link rel="shortcut icon" type="image/png" href="https://rankalytics.com/assets/images/favicon.png"/>
<!-- end favicon -->


<title>Terms of Service | Rankalytics Real-time SEO Marketing Analysis</title>
<meta name="description" content="">

<link rel="author" href="https://plus.google.com/u/0/107956745270665771232/">
<a href="https://plus.google.com/107956745270665771232" rel="publisher"></a>

<META NAME="Geography" CONTENT="Charlotte, North Carolina">
<META NAME="Language" CONTENT="English">
<META NAME="Copyright" CONTENT="Copyright and Trademark by Rankalytics.com">
<META NAME="distribution" CONTENT="Global">
<META NAME="zipcode" CONTENT="28278">
<META NAME="city" CONTENT="Charlotte">
<META NAME="country" CONTENT="United States">
<meta name="coverage" content="Worldwide">
<meta name="rating" content="General">
<meta name="revisit-after" content="7 days">
<meta http-equiv="Expires" content="0">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">


<link href="<?php echo base_url(); ?>assets/home.css" rel="stylesheet" type="text/css">
<link href="<?php echo base_url(); ?>assets/css/radiobuttons.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="//use.typekit.net/pjn4zge.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">

<!-- clicky tracking -->
<script type="text/javascript">
var clicky_site_ids = clicky_site_ids || [];
clicky_site_ids.push(100773884);
(function() {
  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = '//static.getclicky.com/js';
  ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
})();
</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100773884ns.gif" /></p></noscript>
<!-- End clicky tracking -->
</head>
<body>

<?php $this->load->view('home/page-navplacement.php');?>
		
		<div class="ranktracker-topline"></div>

	</div>
</div>

<div class="contactmap"></div>
<span itemscope itemtype="https://schema.org/LocalBusiness">
<div class="bodywrapper">
	<div class="ranktracker-bottomwhitetitle">Terms of Service</div>
	<div class="ranktracker-bottomwhitewrapper">
		<div class="ranktracker-bottomwhitesubcontent" style="margin-bottom:70px;text-align:left;">
		<b>Personal data - Principles</b> <br>
		Rankalytics may collect, process and use personal information from users exclusively in accordance with applicable data protection laws.
		Personal data is any information concerning the personal or material circumstances of an identified or identifiable natural person. This includes primarily the so-called inventory data such as: name, address, email address and phone number also usage data can be personal data if they allow conclusions to be one person - eg Information on the date of your visit to our website, the browser you are using this and other generated data while visiting our site.
		<p> </ p>
		<b>Scope of data collection, processing and use</b> <br>
		We collect, process and use personal data of our users only for the purpose of providing this website. Moreover, collect, process and use your personal data in accordance with any separately by you of consents granted.
		The communication of personal data for the mere visit to this site is not required.
		When you access our site the following information is logged:
		Date and time of access, the URL (web address) of the referring site, the retrieved file, the amount of data transferred, notice of successful retrieval, browser type and browser version, and information about your operating system.
		We use this information for statistical purposes and for internal analysis and to improve our offer. Conclusions about a person are we not possible.
		<p> </ p>
		<b>Analysis tools</b> <br>
		Rankalytics uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). Google Analytics uses. "Cookies", text files that are stored on your computer, to help analyze the use of the website by the user. The information generated by the cookie about your use of Rankalytics are usually transferred to a Google server in the US and stored there. Due to the activation of the IP anonymization on Rankalytics, the IP address of the user from Google will be truncated within Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases will the full IP address transferred to a Google server in the USA and is shortened. On behalf of Rankalytics Google will use this information to evaluate your use of the website, compiling reports on website activity and providing other website activity and internet related services to the website operator. Sent by the browser as part of Google Analytics IP address is not associated with any other data held by Google. The use of cookies can be prevented by appropriate setting of the browser; We point out, however, that in this case, as appropriate, all functions can not be used to full effect of Rankalytics. In addition, you can prevent the data generated by the cookie about the use of the website (incl. The IP address) to Google and the processing of these data by Google, by downloading the available at the following link browser plugin and will install: http://tools.google.com/dlpage/gaoptout?hl=en.
		<p> </ p>
		For more information on Terms of Use and Privacy Policy can be found at http://www.google.com/analytics/terms.html or under http://www.google.com/analytics/privacyoverview.html.  We point out that on this website Google Analytics code "gat._anonymizeIp ();" has been extended to an anonymous collection of IP addresses (so called. IP masking).
		<p> </ p>
		<b>Newsletter</b> <br>
		If you subscribe to our newsletter, we will collect and use your e-mail address to receive our newsletter. Your consent can be revoked at any time with effect for the future, so you can find about any of our newsletters an unsubscribe link.
		The confirmation of your registration via the so-called double opt-in method. For this purpose, we will send you prior to shipment of the first newsletter a confirmation email with a confirmation link. You will receive our newsletter after you click on this confirmation link.
		<p> </ p>
		<b>For information, opposition and cancellation rights</b> <br>
		According to the Federal Data Protection Act you have the right to free information about the data stored about you. In addition, you can object to the creation of pseudonymous user profiles for purposes of advertising, market research or to optimize our website. You always have the option granted consent to the collection, processing or use of your personal data with effect for the future revoked.
		<p>
		Updated 2015.01.25
		</div>

	</div>
	<div class="homefeatures-smallline"></div>
	<div class="checkoutfeatures">There are many great reasons to choose Rankalytics. <a href="/products"><span>View all products now</span></a></div>
	<a href="/products" class="featurescheck"></a>
</div>

<?php $this->load->view('include/mainfooter');?>

<?php $this->load->view('include/login-signup');?>


</body>
</html>